
CREATE OR REPLACE TYPE SALES_INFO_REC IS RECORD (
    SALES_DATE SALES.SALES_DATE%TYPE,
    ORDER_ID SALES.ORDER_ID%TYPE,
    PRODUCT_ID SALES.PRODUCT_ID%TYPE,
    CUSTOMER_ID SALES.CUSTOMER_ID%TYPE,
    QUANTITY SALES.QUANTITY%TYPE
);

-- 1.CREATE AN OBJECT IN THE DATABASE
CREATE OR REPLACE TYPE SALES_ROW AS OBJECT (
    S_DATE DATE,
    S_ORDERID NUMBER,
    S_PRODUCTID NUMBER,
    S_CUSTOMERID NUMBER,
    S_TOTALAMOUNT NUMBER
);


-- NO CREATE A TABLE OF TYPE SALES_ROW
CREATE TYPE SALES_TABLE IS TABLE OF SALES_ROW;