CREATE PROCEDURE DELETE_CUSTOMER(CUSTOMER_ID IN NUMBER)
AS
    CURSOR_NAME INTEGER;
    ROWS_PROCESSED INTEGER;
BEGIN
    --OPEN THE CURSOR
    CURSOR_NAME:= DBMS_SQL.OPEN_CURSOR;
    
    --parsing the sql statement
    DBMS_SQL.PARSE(CURSOR_NAME, 'DELETE FROM CUSTOMER WHERE CUSTOMER_ID = :VAR1', DBMS_SQL.NATIVE);
    
    --binding the variables
    DBMS_SQL.BIND_VARIABLE(CURSOR_NAME, ':VAR1', CUSTOMER_ID);
    
    --executing the cursor
    ROWS_PROCESSED:= DBMS_SQL.EXECUTE(CURSOR_NAME);
    
    --closing the cursor
    DBMS_SQL.CLOSE_CURSOR(CURSOR_NAME);
    
EXCEPTION
    WHEN OTHERS THEN DBMS_SQL.CLOSE_CURSOR(CURSOR_NAME);
END;

SELECT * FROM CUSTOMER;
EXEC DELETE_CUSTOMER(21);