CREATE TRIGGER CUSTOMER_UPDATE_VALUES AFTER UPDATE ON CUSTOMER FOR EACH ROW
DECLARE
    V_USERNAME VARCHAR2(10);
BEGIN
    SELECT USER INTO V_USERNAME FROM DUAL;
    
    INSERT INTO AUDIT_LOG VALUES(
        V_USERNAME, SYSDATE, 
        :OLD.CUSTOMER_ID, :NEW.CUSTOMER_ID, 
        :OLD.FIRST_NAME, :NEW.FIRST_NAME);
END;

select * from audit_log;
SELECT * FROM CUSTOMER;
UPDATE CUSTOMER SET REGION = 'SOUTH' WHERE CUSTOMER_ID = 5;