DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE X(A NUMBER)';
END;
select * from x;
SELECT * FROM SALES;

-- ===========update=
create or replace PROCEDURE UPDATE_SALES_DYNAMIC(P_ID IN NUMBER)
AS
    S_TABLE sales%rowtype;
    
BEGIN
    SELECT * INTO S_TABLE FROM SALES WHERE PRODUCT_ID IN (P_ID);
    EXECUTE IMMEDIATE 'UPDATE SALES SET TOTAL_AMOUNT = TOTAL_AMOUNT * .9
        WHERE PRODUCT_ID = ' || P_ID;
    DBMS_OUTPUT.PUT_LINE('TOTAL_AMOUNT HAS BEEN UPDATED FROM: ' || S_TABLE.TOTAL_AMOUNT ||
        ' TO ' || P_ID);
END;
EXEC UPDATE_SALES_DYNAMIC(105)